# Generated by Django 5.1.1 on 2024-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_parish_contact_parish_location_parish_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
